<!-- TODO algolia properties -->
<script
        src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous"></script>
<script src="$page.base$js/fastclick.js"></script>
<script src="$page.base$js/mini-toggler.js"></script>
<script src="$page.base$js/stickySearch.js"></script>
<script src="$page.base$js/tabPanel.js"></script>
<script src="$page.base$js/refContainer.js"></script>
<!-- syntax highlighting -->
<link rel="stylesheet" type="text/css" href="$page.base$css/prettify.css">
<script type="text/javascript" src="$page.base$js/prettify.js"></script>
<script type="text/javascript" src="$page.base$js/lang-scala.js"></script>
<script type="text/javascript">jQuery(function () {
    PR.prettyPrint()
});</script>