<footer>
    <div class="row">
        <div class="sevencol">
            <div class="footerLinks">
                <ul>
                    <h2>Akka</h2>
                    <!-- TODO are these really the right links (compared to the new site?) -->
                    <li><a class="bright" href="http://akka.io/docs">Documentation</a></li>
                    <li><a class="bright" href="http://akka.io/get-involved">Get Involved</a></li>
                    <li><a class="bright" href="http://blog.akka.io">News</a></li>
                </ul>
                <ul>
                    <h2>Contribute</h2>
                    <li><a class="bright" href="https://groups.google.com/forum/#!forum/akka-user">Mailing List</a></li>
                    <li><a class="bright" href="http://doc.akka.io/docs/akka/current/project/issue-tracking.html">Report a Bug</a></li>
                </ul>
            </div>
            <p class="copyright">
                &copy; $page.properties.("date.year")$ <a href="https://www.lightbend.com/">Lightbend Inc.</a></br>
                Akka is Open Source and available under the Apache 2 License.
            </p>
        </div>
        <div class="fivecol">
            <img src="$page.base$images/akka_icon_reverse.svg" class="footerLogo desktop-only" alt="Akka icon reverse" />
        </div>
    </div>
</footer>